export const TYPE_COLORS = {
    "Bug": "#C4E07B",
    "Dark": "#909090",
    "Dragon": "#9CA5FF",
    "Electric": "#FFF1A1",
    "Fairy": "#FFCFFF",
    "Fighting": "#FFD085",
    "Fire": "#FFA07A",
    "Flying": "#ABDBFF",
    "Ghost": "#BAA3C2",
    "Grass": "#90ED80",
    "Ground": "#D1AF8A",
    "Ice": "#9CF0FF",
    "Normal": "#C0C0C0",
    "Poison": "#D5ACED",
    "Psychic": "#FFA1C4",
    "Rock": "#BDBF97",
    "Steel": "#8BA9B5",
    "Water": "#7DC9FF",
};